name: note_learning_game
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.0.3
  equatable: ^2.0.0
  collection: ^1.15.0

  cupertino_icons: ^1.0.2

  #timer
  circular_countdown_timer: ^0.2.3

  #grid view
  staggered_grid_view_flutter: ^0.0.4

  #state management mobx
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  #json_serializable: ^6.6.0
  #json_annotation: ^4.8.0
  provider: ^6.0.5

  # audio
  audioplayers: ^0.20.1

  #storage shared
  shared_preferences: ^2.0.18
  easy_localization: ^3.0.1

  # touchable opacity
  touchable_opacity: ^1.2.0
  # device_preview: ^1.1.0
  google_fonts: ^4.0.3
  # app icon
  flutter_launcher_icons: ^0.12.0
  # splash 
  flutter_native_splash: ^2.2.19
  # package name
  change_app_package_name: ^1.1.0
  
  # ads
  google_mobile_ads: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: 2.0.3

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash2.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/example_data.json
    - assets/piano-mp3/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
